# Generated by Django 2.2.11 on 2020-03-17 12:10

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound_teststand_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('NODELETE', models.BooleanField(default=False)),
                ('Sent_by', models.CharField(max_length=200)),
                ('command_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('Validation_failed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Teststand packages',
            },
        ),
        migrations.CreateModel(
            name='ND_TS',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TimeStamp', models.CharField(blank=True, max_length=200, null=True)),
                ('NoDelete', models.BooleanField(default=False)),
                ('StatusCode', models.CharField(default='empty', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'NoDelete & TimeStamp',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_requested_by', models.CharField(max_length=100)),
                ('job_received_time', models.DateTimeField(auto_now=True)),
                ('job_NODELETE', models.BooleanField(default=False)),
                ('command_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('parameter_obj', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_obj', django.contrib.postgres.fields.jsonb.JSONField()),
                ('embedded_file_format', models.CharField(max_length=20)),
                ('embedded_file', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('latest_status_code', models.CharField(choices=[('200', '200 OK'), ('202', '202 Received and accepted'), ('400', '400 Bad request'), ('404', '404 Not found'), ('405', '405 Method not allowed'), ('500', '500 Internal error on device')], default='200', max_length=3)),
                ('latest_status_update', models.DateTimeField(auto_now=True)),
                ('latest_power_code', models.CharField(choices=[('600', '600 Device on'), ('610', '610 Device in hibernation'), ('620', '620 Device off')], default='620', max_length=3)),
                ('latest_power_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_payload', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_payload', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_stand_parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parameter_name', models.CharField(default='Empty', max_length=100)),
                ('Parameter_value', models.CharField(default='Empty', max_length=100)),
                ('Inbound_teststand_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='demo_module.Inbound_teststand_package')),
            ],
            options={
                'verbose_name_plural': 'Teststand parameters',
            },
        ),
        migrations.CreateModel(
            name='Test_stand_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_name', models.CharField(max_length=100, null=True)),
                ('Data_points', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('Inbound_teststand_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='demo_module.Inbound_teststand_package')),
            ],
            options={
                'verbose_name_plural': 'Teststand data types',
            },
        ),
    ]
