# Generated by Django 2.2.10 on 2020-03-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_stand_parameters',
            old_name='Inbound_teststand_packag',
            new_name='Inbound_teststand_package',
        ),
    ]
