# Generated by Django 2.2.10 on 2020-03-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0004_inbound_teststand_package_schema_validation_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbound_teststand_package',
            old_name='schema_validation_result',
            new_name='Validation_failed',
        ),
    ]
