# Generated by Django 2.2.10 on 2020-03-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0005_auto_20200302_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound_teststand_package',
            name='id',
        ),
        migrations.AlterField(
            model_name='inbound_teststand_package',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
