# Generated by Django 2.2.10 on 2020-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_module', '0006_auto_20200302_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound_teststand_package',
            name='Timestamp',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
